# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven-Build-Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
        
      - name: Build Docker Image with Maven
        run: mvn package
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout: true
          
      - name: Push Docker Image to Hub Repos   
        run: |
          docker tag ${{secrets.DOCKER_USER}}/spring-web:latest ${{secrets.DOCKER_USER}}/spring-web:${{github.sha}}
          docker push ${{secrets.DOCKER_USER}}/spring-web:${{github.sha}}
          
      - name: Trigger CI
        uses: InformaticsMatters/trigger-ci-action@1.0.1
        with:
          ci-owner: peter-hst
          ci-repository: spring-web-devops
          ci-ref: refs/heads/main
          ci-user: peter-hst
          ci-user-token: ${{ secrets.CD_TOKEN }}
          ci-name: CD
          ci-inputs: >-
            image=${{ secrets.DOCKER_USER }}/spring-web
            sha-tag=${{ github.sha }}
